### ISSUE TITLE
A substantial waiting time when opening CDE folder

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-workspace-server#15]
If you open the "All / Shared / CDE" folder in the production server, you will notice a substantial delay (waiting time) to load the CDE list.

**Comment by graybeal** [comment]
Half the issue is the delay, and the other half is the lack of UI feedback that indicates there is a delay. If we have the indication, than the delay is at least tolerable.
Per general UI guidelines we should quickly pop up some kind of icon or message to indicate that the system is working and more information is pending. (True for any display that doesn't load in the first half-second or so.)
